global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  - job_name: 'zipkin'
    static_configs:
      - targets: [ 'zipkin:9411' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]
