services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: voxxcar-postgres
    environment:
      POSTGRES_DB: voxxcar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./voxx-car-server/internal/framework/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voxxcar-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: voxxcar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voxxcar-network

  # Go Backend Server
  backend:
    build:
      context: ./voxx-car-server
      dockerfile: Dockerfile
      target: production
    container_name: voxxcar-backend
    environment:
      - APP_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=voxxcar
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - voxxcar-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./voxx-car-client
      dockerfile: Dockerfile
      target: production
    container_name: voxxcar-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - voxxcar-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  voxxcar-network:
    driver: bridge
