version: "3.8"

services:
  app:
    build:
      context: ./voxx-car-server
      dockerfile: Dockerfile
    container_name: voxx-car-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    networks:
      - voxx-car-network

  client:
    build:
      context: ./voxx-car-client
      dockerfile: Dockerfile
    container_name: voxx-car-ui
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - voxx-car-network

  postgres:
    image: postgres:15
    container_name: voxx-car-postgres-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123!
      - POSTGRES_DB=voxxcar
    networks:
      - voxx-car-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: voxx-car-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - voxx-car-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: voxx-car-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - voxx-car-network

networks:
  voxx-car-network:
    driver: bridge
