apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: voxx-spring
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: voxx-car-server
      context: voxx-car-server
      docker:
        dockerfile: Dockerfile
    - image: voxx-car-client
      context: voxx-car-client
      docker:
        dockerfile: Dockerfile
  local:
    push: false
