apiVersion: v1
kind: ConfigMap
metadata:
  name: couchbase-entrypoint
  namespace: voxx
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e
    CB_ADMIN_USERNAME="${CB_ADMIN_USERNAME:-Administrator}"
    CB_ADMIN_PASSWORD="${CB_ADMIN_PASSWORD:-password}"
    CB_BUCKET_NAME="${CB_BUCKET_NAME:-car-bucket}"
    CB_BUCKET_RAMSIZE="${CB_BUCKET_RAMSIZE:-512}"
    CB_USER="${CB_USER:-caruser}"
    CB_USER_PASSWORD="${CB_USER_PASSWORD:-caruserpass}"
    CB_HOST="localhost"
    /entrypoint.sh couchbase-server &
    echo "Waiting for Couchbase Server to be ready..."
    until curl -s -u $CB_ADMIN_USERNAME:$CB_ADMIN_PASSWORD http://$CB_HOST:8091/pools > /dev/null; do
      sleep 5
      echo "Waiting..."
    done
    echo "Initializing cluster..."
    couchbase-cli cluster-init -c $CB_HOST:8091 \
      --cluster-username $CB_ADMIN_USERNAME \
      --cluster-password $CB_ADMIN_PASSWORD \
      --services data,index,query \
      --cluster-ramsize $CB_BUCKET_RAMSIZE \
      --cluster-index-ramsize 256
    echo "Creating bucket (if not exists)..."
    couchbase-cli bucket-create -c $CB_HOST:8091 \
      --username $CB_ADMIN_USERNAME --password $CB_ADMIN_PASSWORD \
      --bucket $CB_BUCKET_NAME --bucket-type couchbase --bucket-ramsize $CB_BUCKET_RAMSIZE --enable-flush 1 || true
    echo "Creating user (if not exists)..."
    couchbase-cli user-manage -c $CB_HOST:8091 \
      --username $CB_ADMIN_USERNAME --password $CB_ADMIN_PASSWORD \
      --set --rbac-username $CB_USER --rbac-password $CB_USER_PASSWORD \
      --roles bucket_full_access[$CB_BUCKET_NAME] --auth-domain local || true
    echo "Setup done. Keeping container running..."
    tail -f /dev/null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-service
  namespace: voxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-service
  template:
    metadata:
      labels:
        app: couchbase-service
    spec:
      containers:
        - name: couchbase
          image: couchbase:community
          ports:
            - containerPort: 8091
            - containerPort: 8092
            - containerPort: 8093
            - containerPort: 8094
            - containerPort: 11210
          env:
            - name: CB_ADMIN_USERNAME
              value: Administrator
            - name: CB_ADMIN_PASSWORD
              value: password
            - name: CB_BUCKET_NAME
              value: car-bucket
            - name: CB_USER
              value: caruser
            - name: CB_USER_PASSWORD
              value: caruserpass
            - name: CB_BUCKET_RAMSIZE
              value: "512"
          volumeMounts:
            - name: entrypoint
              mountPath: /opt/couchbase/entrypoint.sh
              subPath: entrypoint.sh
      volumes:
        - name: entrypoint
          configMap:
            name: couchbase-entrypoint
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
  namespace: voxx
spec:
  selector:
    app: couchbase-service
  ports:
    - name: admin-8091
      port: 8091
      targetPort: 8091
    - name: admin-8092
      port: 8092
      targetPort: 8092
    - name: query-8093
      port: 8093
      targetPort: 8093
    - name: search-8094
      port: 8094
      targetPort: 8094
    - name: data-11210
      port: 11210
      targetPort: 11210

