apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-db-pvc
  namespace: voxx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-db
  namespace: voxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-db
  template:
    metadata:
      labels:
        app: kc-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: keycloak
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kc-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kc-db
  namespace: voxx
spec:
  selector:
    app: kc-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

