/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Layout_authenticatedRouteImport } from './routes/_layout_authenticated'
import { Route as Layout_authRouteImport } from './routes/_layout_auth'
import { Route as Layout_authenticatedIndexRouteImport } from './routes/_layout_authenticated/index'
import { Route as Layout_authLoginRouteImport } from './routes/_layout_auth/login'
import { Route as Layout_authenticatedMarkaIndexRouteImport } from './routes/_layout_authenticated/marka/index'
import { Route as Layout_authenticatedDemosDemoTanstackQueryRouteImport } from './routes/_layout_authenticated/demos/demo.tanstack-query'
import { Route as Layout_authenticatedDemosDemoFormSimpleRouteImport } from './routes/_layout_authenticated/demos/demo.form.simple'
import { Route as Layout_authenticatedDemosDemoFormAddressRouteImport } from './routes/_layout_authenticated/demos/demo.form.address'

const Layout_authenticatedRoute = Layout_authenticatedRouteImport.update({
  id: '/_layout_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Layout_authRoute = Layout_authRouteImport.update({
  id: '/_layout_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Layout_authenticatedIndexRoute =
  Layout_authenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Layout_authenticatedRoute,
  } as any)
const Layout_authLoginRoute = Layout_authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => Layout_authRoute,
} as any)
const Layout_authenticatedMarkaIndexRoute =
  Layout_authenticatedMarkaIndexRouteImport.update({
    id: '/marka/',
    path: '/marka/',
    getParentRoute: () => Layout_authenticatedRoute,
  } as any)
const Layout_authenticatedDemosDemoTanstackQueryRoute =
  Layout_authenticatedDemosDemoTanstackQueryRouteImport.update({
    id: '/demos/demo/tanstack-query',
    path: '/demos/demo/tanstack-query',
    getParentRoute: () => Layout_authenticatedRoute,
  } as any)
const Layout_authenticatedDemosDemoFormSimpleRoute =
  Layout_authenticatedDemosDemoFormSimpleRouteImport.update({
    id: '/demos/demo/form/simple',
    path: '/demos/demo/form/simple',
    getParentRoute: () => Layout_authenticatedRoute,
  } as any)
const Layout_authenticatedDemosDemoFormAddressRoute =
  Layout_authenticatedDemosDemoFormAddressRouteImport.update({
    id: '/demos/demo/form/address',
    path: '/demos/demo/form/address',
    getParentRoute: () => Layout_authenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof Layout_authenticatedRouteWithChildren
  '/login': typeof Layout_authLoginRoute
  '/': typeof Layout_authenticatedIndexRoute
  '/marka': typeof Layout_authenticatedMarkaIndexRoute
  '/demos/demo/tanstack-query': typeof Layout_authenticatedDemosDemoTanstackQueryRoute
  '/demos/demo/form/address': typeof Layout_authenticatedDemosDemoFormAddressRoute
  '/demos/demo/form/simple': typeof Layout_authenticatedDemosDemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '': typeof Layout_authRouteWithChildren
  '/login': typeof Layout_authLoginRoute
  '/': typeof Layout_authenticatedIndexRoute
  '/marka': typeof Layout_authenticatedMarkaIndexRoute
  '/demos/demo/tanstack-query': typeof Layout_authenticatedDemosDemoTanstackQueryRoute
  '/demos/demo/form/address': typeof Layout_authenticatedDemosDemoFormAddressRoute
  '/demos/demo/form/simple': typeof Layout_authenticatedDemosDemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout_auth': typeof Layout_authRouteWithChildren
  '/_layout_authenticated': typeof Layout_authenticatedRouteWithChildren
  '/_layout_auth/login': typeof Layout_authLoginRoute
  '/_layout_authenticated/': typeof Layout_authenticatedIndexRoute
  '/_layout_authenticated/marka/': typeof Layout_authenticatedMarkaIndexRoute
  '/_layout_authenticated/demos/demo/tanstack-query': typeof Layout_authenticatedDemosDemoTanstackQueryRoute
  '/_layout_authenticated/demos/demo/form/address': typeof Layout_authenticatedDemosDemoFormAddressRoute
  '/_layout_authenticated/demos/demo/form/simple': typeof Layout_authenticatedDemosDemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/marka'
    | '/demos/demo/tanstack-query'
    | '/demos/demo/form/address'
    | '/demos/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/'
    | '/marka'
    | '/demos/demo/tanstack-query'
    | '/demos/demo/form/address'
    | '/demos/demo/form/simple'
  id:
    | '__root__'
    | '/_layout_auth'
    | '/_layout_authenticated'
    | '/_layout_auth/login'
    | '/_layout_authenticated/'
    | '/_layout_authenticated/marka/'
    | '/_layout_authenticated/demos/demo/tanstack-query'
    | '/_layout_authenticated/demos/demo/form/address'
    | '/_layout_authenticated/demos/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Layout_authRoute: typeof Layout_authRouteWithChildren
  Layout_authenticatedRoute: typeof Layout_authenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout_authenticated': {
      id: '/_layout_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Layout_authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout_auth': {
      id: '/_layout_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Layout_authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout_authenticated/': {
      id: '/_layout_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Layout_authenticatedIndexRouteImport
      parentRoute: typeof Layout_authenticatedRoute
    }
    '/_layout_auth/login': {
      id: '/_layout_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof Layout_authLoginRouteImport
      parentRoute: typeof Layout_authRoute
    }
    '/_layout_authenticated/marka/': {
      id: '/_layout_authenticated/marka/'
      path: '/marka'
      fullPath: '/marka'
      preLoaderRoute: typeof Layout_authenticatedMarkaIndexRouteImport
      parentRoute: typeof Layout_authenticatedRoute
    }
    '/_layout_authenticated/demos/demo/tanstack-query': {
      id: '/_layout_authenticated/demos/demo/tanstack-query'
      path: '/demos/demo/tanstack-query'
      fullPath: '/demos/demo/tanstack-query'
      preLoaderRoute: typeof Layout_authenticatedDemosDemoTanstackQueryRouteImport
      parentRoute: typeof Layout_authenticatedRoute
    }
    '/_layout_authenticated/demos/demo/form/simple': {
      id: '/_layout_authenticated/demos/demo/form/simple'
      path: '/demos/demo/form/simple'
      fullPath: '/demos/demo/form/simple'
      preLoaderRoute: typeof Layout_authenticatedDemosDemoFormSimpleRouteImport
      parentRoute: typeof Layout_authenticatedRoute
    }
    '/_layout_authenticated/demos/demo/form/address': {
      id: '/_layout_authenticated/demos/demo/form/address'
      path: '/demos/demo/form/address'
      fullPath: '/demos/demo/form/address'
      preLoaderRoute: typeof Layout_authenticatedDemosDemoFormAddressRouteImport
      parentRoute: typeof Layout_authenticatedRoute
    }
  }
}

interface Layout_authRouteChildren {
  Layout_authLoginRoute: typeof Layout_authLoginRoute
}

const Layout_authRouteChildren: Layout_authRouteChildren = {
  Layout_authLoginRoute: Layout_authLoginRoute,
}

const Layout_authRouteWithChildren = Layout_authRoute._addFileChildren(
  Layout_authRouteChildren,
)

interface Layout_authenticatedRouteChildren {
  Layout_authenticatedIndexRoute: typeof Layout_authenticatedIndexRoute
  Layout_authenticatedMarkaIndexRoute: typeof Layout_authenticatedMarkaIndexRoute
  Layout_authenticatedDemosDemoTanstackQueryRoute: typeof Layout_authenticatedDemosDemoTanstackQueryRoute
  Layout_authenticatedDemosDemoFormAddressRoute: typeof Layout_authenticatedDemosDemoFormAddressRoute
  Layout_authenticatedDemosDemoFormSimpleRoute: typeof Layout_authenticatedDemosDemoFormSimpleRoute
}

const Layout_authenticatedRouteChildren: Layout_authenticatedRouteChildren = {
  Layout_authenticatedIndexRoute: Layout_authenticatedIndexRoute,
  Layout_authenticatedMarkaIndexRoute: Layout_authenticatedMarkaIndexRoute,
  Layout_authenticatedDemosDemoTanstackQueryRoute:
    Layout_authenticatedDemosDemoTanstackQueryRoute,
  Layout_authenticatedDemosDemoFormAddressRoute:
    Layout_authenticatedDemosDemoFormAddressRoute,
  Layout_authenticatedDemosDemoFormSimpleRoute:
    Layout_authenticatedDemosDemoFormSimpleRoute,
}

const Layout_authenticatedRouteWithChildren =
  Layout_authenticatedRoute._addFileChildren(Layout_authenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Layout_authRoute: Layout_authRouteWithChildren,
  Layout_authenticatedRoute: Layout_authenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
