/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticationRouteImport } from './routes/_authentication'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticationLoginRouteImport } from './routes/_authentication/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedModelIndexRouteImport } from './routes/_authenticated/model/index'
import { Route as AuthenticatedMarkaIndexRouteImport } from './routes/_authenticated/marka/index'
import { Route as AuthenticatedFirmaIndexRouteImport } from './routes/_authenticated/firma/index'
import { Route as AuthenticatedAracFiloIndexRouteImport } from './routes/_authenticated/arac-filo/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutRouteImport } from './routes/_authenticated/firma/$firmaId/_layout'
import { Route as AuthenticatedFirmaFirmaIdLayoutIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/index'
import { Route as AuthenticatedAracFiloForm_layoutOlusturIndexRouteImport } from './routes/_authenticated/arac-filo/_form_layout/olustur/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutDetayIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/detay/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/arac-kullanan/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutAdresIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/adres/index'

const AuthenticatedFirmaFirmaIdRouteImport = createFileRoute(
  '/_authenticated/firma/$firmaId',
)()

const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirmaFirmaIdRoute =
  AuthenticatedFirmaFirmaIdRouteImport.update({
    id: '/firma/$firmaId',
    path: '/firma/$firmaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelIndexRoute = AuthenticatedModelIndexRouteImport.update({
  id: '/model/',
  path: '/model/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarkaIndexRoute = AuthenticatedMarkaIndexRouteImport.update({
  id: '/marka/',
  path: '/marka/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirmaIndexRoute = AuthenticatedFirmaIndexRouteImport.update({
  id: '/firma/',
  path: '/firma/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAracFiloIndexRoute =
  AuthenticatedAracFiloIndexRouteImport.update({
    id: '/arac-filo/',
    path: '/arac-filo/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutRoute =
  AuthenticatedFirmaFirmaIdLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedFirmaFirmaIdRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)
const AuthenticatedAracFiloForm_layoutOlusturIndexRoute =
  AuthenticatedAracFiloForm_layoutOlusturIndexRouteImport.update({
    id: '/arac-filo/_form_layout/olustur/',
    path: '/arac-filo/olustur/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutDetayIndexRouteImport.update({
    id: '/detay/',
    path: '/detay/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRouteImport.update({
    id: '/arac-kullanan/',
    path: '/arac-kullanan/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutAdresIndexRouteImport.update({
    id: '/adres/',
    path: '/adres/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof AuthenticationLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/arac-filo': typeof AuthenticatedAracFiloIndexRoute
  '/firma': typeof AuthenticatedFirmaIndexRoute
  '/marka': typeof AuthenticatedMarkaIndexRoute
  '/model': typeof AuthenticatedModelIndexRoute
  '/firma/$firmaId': typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
  '/arac-filo/olustur': typeof AuthenticatedAracFiloForm_layoutOlusturIndexRoute
  '/firma/$firmaId/': typeof AuthenticatedFirmaFirmaIdLayoutIndexRoute
  '/firma/$firmaId/adres': typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  '/firma/$firmaId/arac-kullanan': typeof AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute
  '/firma/$firmaId/detay': typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
}
export interface FileRoutesByTo {
  '': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof AuthenticationLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/arac-filo': typeof AuthenticatedAracFiloIndexRoute
  '/firma': typeof AuthenticatedFirmaIndexRoute
  '/marka': typeof AuthenticatedMarkaIndexRoute
  '/model': typeof AuthenticatedModelIndexRoute
  '/firma/$firmaId': typeof AuthenticatedFirmaFirmaIdLayoutIndexRoute
  '/arac-filo/olustur': typeof AuthenticatedAracFiloForm_layoutOlusturIndexRoute
  '/firma/$firmaId/adres': typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  '/firma/$firmaId/arac-kullanan': typeof AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute
  '/firma/$firmaId/detay': typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/arac-filo/': typeof AuthenticatedAracFiloIndexRoute
  '/_authenticated/firma/': typeof AuthenticatedFirmaIndexRoute
  '/_authenticated/marka/': typeof AuthenticatedMarkaIndexRoute
  '/_authenticated/model/': typeof AuthenticatedModelIndexRoute
  '/_authenticated/firma/$firmaId': typeof AuthenticatedFirmaFirmaIdRouteWithChildren
  '/_authenticated/firma/$firmaId/_layout': typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
  '/_authenticated/arac-filo/_form_layout/olustur/': typeof AuthenticatedAracFiloForm_layoutOlusturIndexRoute
  '/_authenticated/firma/$firmaId/_layout/': typeof AuthenticatedFirmaFirmaIdLayoutIndexRoute
  '/_authenticated/firma/$firmaId/_layout/adres/': typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  '/_authenticated/firma/$firmaId/_layout/arac-kullanan/': typeof AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute
  '/_authenticated/firma/$firmaId/_layout/detay/': typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/login'
    | '/'
    | '/arac-filo'
    | '/firma'
    | '/marka'
    | '/model'
    | '/firma/$firmaId'
    | '/arac-filo/olustur'
    | '/firma/$firmaId/'
    | '/firma/$firmaId/adres'
    | '/firma/$firmaId/arac-kullanan'
    | '/firma/$firmaId/detay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/login'
    | '/'
    | '/arac-filo'
    | '/firma'
    | '/marka'
    | '/model'
    | '/firma/$firmaId'
    | '/arac-filo/olustur'
    | '/firma/$firmaId/adres'
    | '/firma/$firmaId/arac-kullanan'
    | '/firma/$firmaId/detay'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authentication'
    | '/_authenticated/dashboard'
    | '/_authentication/login'
    | '/_authenticated/'
    | '/_authenticated/arac-filo/'
    | '/_authenticated/firma/'
    | '/_authenticated/marka/'
    | '/_authenticated/model/'
    | '/_authenticated/firma/$firmaId'
    | '/_authenticated/firma/$firmaId/_layout'
    | '/_authenticated/arac-filo/_form_layout/olustur/'
    | '/_authenticated/firma/$firmaId/_layout/'
    | '/_authenticated/firma/$firmaId/_layout/adres/'
    | '/_authenticated/firma/$firmaId/_layout/arac-kullanan/'
    | '/_authenticated/firma/$firmaId/_layout/detay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/$firmaId': {
      id: '/_authenticated/firma/$firmaId'
      path: '/firma/$firmaId'
      fullPath: '/firma/$firmaId'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model/': {
      id: '/_authenticated/model/'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof AuthenticatedModelIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marka/': {
      id: '/_authenticated/marka/'
      path: '/marka'
      fullPath: '/marka'
      preLoaderRoute: typeof AuthenticatedMarkaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/': {
      id: '/_authenticated/firma/'
      path: '/firma'
      fullPath: '/firma'
      preLoaderRoute: typeof AuthenticatedFirmaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arac-filo/': {
      id: '/_authenticated/arac-filo/'
      path: '/arac-filo'
      fullPath: '/arac-filo'
      preLoaderRoute: typeof AuthenticatedAracFiloIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/$firmaId/_layout': {
      id: '/_authenticated/firma/$firmaId/_layout'
      path: '/firma/$firmaId'
      fullPath: '/firma/$firmaId'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdRoute
    }
    '/_authenticated/firma/$firmaId/_layout/': {
      id: '/_authenticated/firma/$firmaId/_layout/'
      path: '/'
      fullPath: '/firma/$firmaId/'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
    '/_authenticated/arac-filo/_form_layout/olustur/': {
      id: '/_authenticated/arac-filo/_form_layout/olustur/'
      path: '/arac-filo/olustur'
      fullPath: '/arac-filo/olustur'
      preLoaderRoute: typeof AuthenticatedAracFiloForm_layoutOlusturIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/$firmaId/_layout/detay/': {
      id: '/_authenticated/firma/$firmaId/_layout/detay/'
      path: '/detay'
      fullPath: '/firma/$firmaId/detay'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
    '/_authenticated/firma/$firmaId/_layout/arac-kullanan/': {
      id: '/_authenticated/firma/$firmaId/_layout/arac-kullanan/'
      path: '/arac-kullanan'
      fullPath: '/firma/$firmaId/arac-kullanan'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
    '/_authenticated/firma/$firmaId/_layout/adres/': {
      id: '/_authenticated/firma/$firmaId/_layout/adres/'
      path: '/adres'
      fullPath: '/firma/$firmaId/adres'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
  }
}

interface AuthenticatedFirmaFirmaIdLayoutRouteChildren {
  AuthenticatedFirmaFirmaIdLayoutIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutIndexRoute
  AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute
  AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
}

const AuthenticatedFirmaFirmaIdLayoutRouteChildren: AuthenticatedFirmaFirmaIdLayoutRouteChildren =
  {
    AuthenticatedFirmaFirmaIdLayoutIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutIndexRoute,
    AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute,
    AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutAracKullananIndexRoute,
    AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute,
  }

const AuthenticatedFirmaFirmaIdLayoutRouteWithChildren =
  AuthenticatedFirmaFirmaIdLayoutRoute._addFileChildren(
    AuthenticatedFirmaFirmaIdLayoutRouteChildren,
  )

interface AuthenticatedFirmaFirmaIdRouteChildren {
  AuthenticatedFirmaFirmaIdLayoutRoute: typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
}

const AuthenticatedFirmaFirmaIdRouteChildren: AuthenticatedFirmaFirmaIdRouteChildren =
  {
    AuthenticatedFirmaFirmaIdLayoutRoute:
      AuthenticatedFirmaFirmaIdLayoutRouteWithChildren,
  }

const AuthenticatedFirmaFirmaIdRouteWithChildren =
  AuthenticatedFirmaFirmaIdRoute._addFileChildren(
    AuthenticatedFirmaFirmaIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAracFiloIndexRoute: typeof AuthenticatedAracFiloIndexRoute
  AuthenticatedFirmaIndexRoute: typeof AuthenticatedFirmaIndexRoute
  AuthenticatedMarkaIndexRoute: typeof AuthenticatedMarkaIndexRoute
  AuthenticatedModelIndexRoute: typeof AuthenticatedModelIndexRoute
  AuthenticatedFirmaFirmaIdRoute: typeof AuthenticatedFirmaFirmaIdRouteWithChildren
  AuthenticatedAracFiloForm_layoutOlusturIndexRoute: typeof AuthenticatedAracFiloForm_layoutOlusturIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAracFiloIndexRoute: AuthenticatedAracFiloIndexRoute,
  AuthenticatedFirmaIndexRoute: AuthenticatedFirmaIndexRoute,
  AuthenticatedMarkaIndexRoute: AuthenticatedMarkaIndexRoute,
  AuthenticatedModelIndexRoute: AuthenticatedModelIndexRoute,
  AuthenticatedFirmaFirmaIdRoute: AuthenticatedFirmaFirmaIdRouteWithChildren,
  AuthenticatedAracFiloForm_layoutOlusturIndexRoute:
    AuthenticatedAracFiloForm_layoutOlusturIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
