/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticationRouteImport } from './routes/_authentication'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticationLoginRouteImport } from './routes/_authentication/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedModelIndexRouteImport } from './routes/_authenticated/model/index'
import { Route as AuthenticatedMarkaIndexRouteImport } from './routes/_authenticated/marka/index'
import { Route as AuthenticatedFirmaIndexRouteImport } from './routes/_authenticated/firma/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutRouteImport } from './routes/_authenticated/firma/$firmaId/_layout'
import { Route as AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/kullanilan-araclar/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutDetayIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/detay/index'
import { Route as AuthenticatedFirmaFirmaIdLayoutAdresIndexRouteImport } from './routes/_authenticated/firma/$firmaId/_layout/adres/index'

const AuthenticatedFirmaFirmaIdRouteImport = createFileRoute(
  '/_authenticated/firma/$firmaId',
)()

const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirmaFirmaIdRoute =
  AuthenticatedFirmaFirmaIdRouteImport.update({
    id: '/firma/$firmaId',
    path: '/firma/$firmaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelIndexRoute = AuthenticatedModelIndexRouteImport.update({
  id: '/model/',
  path: '/model/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarkaIndexRoute = AuthenticatedMarkaIndexRouteImport.update({
  id: '/marka/',
  path: '/marka/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirmaIndexRoute = AuthenticatedFirmaIndexRouteImport.update({
  id: '/firma/',
  path: '/firma/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirmaFirmaIdLayoutRoute =
  AuthenticatedFirmaFirmaIdLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedFirmaFirmaIdRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRouteImport.update({
    id: '/kullanilan-araclar/',
    path: '/kullanilan-araclar/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutDetayIndexRouteImport.update({
    id: '/detay/',
    path: '/detay/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)
const AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute =
  AuthenticatedFirmaFirmaIdLayoutAdresIndexRouteImport.update({
    id: '/adres/',
    path: '/adres/',
    getParentRoute: () => AuthenticatedFirmaFirmaIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof AuthenticationLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/firma': typeof AuthenticatedFirmaIndexRoute
  '/marka': typeof AuthenticatedMarkaIndexRoute
  '/model': typeof AuthenticatedModelIndexRoute
  '/firma/$firmaId': typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
  '/firma/$firmaId/adres': typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  '/firma/$firmaId/detay': typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
  '/firma/$firmaId/kullanilan-araclar': typeof AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute
}
export interface FileRoutesByTo {
  '': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof AuthenticationLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/firma': typeof AuthenticatedFirmaIndexRoute
  '/marka': typeof AuthenticatedMarkaIndexRoute
  '/model': typeof AuthenticatedModelIndexRoute
  '/firma/$firmaId': typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
  '/firma/$firmaId/adres': typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  '/firma/$firmaId/detay': typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
  '/firma/$firmaId/kullanilan-araclar': typeof AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/firma/': typeof AuthenticatedFirmaIndexRoute
  '/_authenticated/marka/': typeof AuthenticatedMarkaIndexRoute
  '/_authenticated/model/': typeof AuthenticatedModelIndexRoute
  '/_authenticated/firma/$firmaId': typeof AuthenticatedFirmaFirmaIdRouteWithChildren
  '/_authenticated/firma/$firmaId/_layout': typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
  '/_authenticated/firma/$firmaId/_layout/adres/': typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  '/_authenticated/firma/$firmaId/_layout/detay/': typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
  '/_authenticated/firma/$firmaId/_layout/kullanilan-araclar/': typeof AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/login'
    | '/'
    | '/firma'
    | '/marka'
    | '/model'
    | '/firma/$firmaId'
    | '/firma/$firmaId/adres'
    | '/firma/$firmaId/detay'
    | '/firma/$firmaId/kullanilan-araclar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/login'
    | '/'
    | '/firma'
    | '/marka'
    | '/model'
    | '/firma/$firmaId'
    | '/firma/$firmaId/adres'
    | '/firma/$firmaId/detay'
    | '/firma/$firmaId/kullanilan-araclar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authentication'
    | '/_authenticated/dashboard'
    | '/_authentication/login'
    | '/_authenticated/'
    | '/_authenticated/firma/'
    | '/_authenticated/marka/'
    | '/_authenticated/model/'
    | '/_authenticated/firma/$firmaId'
    | '/_authenticated/firma/$firmaId/_layout'
    | '/_authenticated/firma/$firmaId/_layout/adres/'
    | '/_authenticated/firma/$firmaId/_layout/detay/'
    | '/_authenticated/firma/$firmaId/_layout/kullanilan-araclar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/$firmaId': {
      id: '/_authenticated/firma/$firmaId'
      path: '/firma/$firmaId'
      fullPath: '/firma/$firmaId'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model/': {
      id: '/_authenticated/model/'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof AuthenticatedModelIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marka/': {
      id: '/_authenticated/marka/'
      path: '/marka'
      fullPath: '/marka'
      preLoaderRoute: typeof AuthenticatedMarkaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/': {
      id: '/_authenticated/firma/'
      path: '/firma'
      fullPath: '/firma'
      preLoaderRoute: typeof AuthenticatedFirmaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firma/$firmaId/_layout': {
      id: '/_authenticated/firma/$firmaId/_layout'
      path: '/firma/$firmaId'
      fullPath: '/firma/$firmaId'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdRoute
    }
    '/_authenticated/firma/$firmaId/_layout/kullanilan-araclar/': {
      id: '/_authenticated/firma/$firmaId/_layout/kullanilan-araclar/'
      path: '/kullanilan-araclar'
      fullPath: '/firma/$firmaId/kullanilan-araclar'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
    '/_authenticated/firma/$firmaId/_layout/detay/': {
      id: '/_authenticated/firma/$firmaId/_layout/detay/'
      path: '/detay'
      fullPath: '/firma/$firmaId/detay'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
    '/_authenticated/firma/$firmaId/_layout/adres/': {
      id: '/_authenticated/firma/$firmaId/_layout/adres/'
      path: '/adres'
      fullPath: '/firma/$firmaId/adres'
      preLoaderRoute: typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRouteImport
      parentRoute: typeof AuthenticatedFirmaFirmaIdLayoutRoute
    }
  }
}

interface AuthenticatedFirmaFirmaIdLayoutRouteChildren {
  AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute
  AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute
  AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute: typeof AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute
}

const AuthenticatedFirmaFirmaIdLayoutRouteChildren: AuthenticatedFirmaFirmaIdLayoutRouteChildren =
  {
    AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutAdresIndexRoute,
    AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutDetayIndexRoute,
    AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute:
      AuthenticatedFirmaFirmaIdLayoutKullanilanAraclarIndexRoute,
  }

const AuthenticatedFirmaFirmaIdLayoutRouteWithChildren =
  AuthenticatedFirmaFirmaIdLayoutRoute._addFileChildren(
    AuthenticatedFirmaFirmaIdLayoutRouteChildren,
  )

interface AuthenticatedFirmaFirmaIdRouteChildren {
  AuthenticatedFirmaFirmaIdLayoutRoute: typeof AuthenticatedFirmaFirmaIdLayoutRouteWithChildren
}

const AuthenticatedFirmaFirmaIdRouteChildren: AuthenticatedFirmaFirmaIdRouteChildren =
  {
    AuthenticatedFirmaFirmaIdLayoutRoute:
      AuthenticatedFirmaFirmaIdLayoutRouteWithChildren,
  }

const AuthenticatedFirmaFirmaIdRouteWithChildren =
  AuthenticatedFirmaFirmaIdRoute._addFileChildren(
    AuthenticatedFirmaFirmaIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFirmaIndexRoute: typeof AuthenticatedFirmaIndexRoute
  AuthenticatedMarkaIndexRoute: typeof AuthenticatedMarkaIndexRoute
  AuthenticatedModelIndexRoute: typeof AuthenticatedModelIndexRoute
  AuthenticatedFirmaFirmaIdRoute: typeof AuthenticatedFirmaFirmaIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFirmaIndexRoute: AuthenticatedFirmaIndexRoute,
  AuthenticatedMarkaIndexRoute: AuthenticatedMarkaIndexRoute,
  AuthenticatedModelIndexRoute: AuthenticatedModelIndexRoute,
  AuthenticatedFirmaFirmaIdRoute: AuthenticatedFirmaFirmaIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
