{
 "title": "Zipkin / Prometheus",
 "description": "Visualize Prometheus metrics exported by OpenZipkin (http://zipkin.io/).",
 "tags": [
  "zipkin",
  "tracing"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Zipkin instances",
    "query": "label_values(http_server_requests_seconds_bucket{job=\"zipkin\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Trace msg/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(level)(rate(log4j2_events_total{job=\"zipkin\",level=\"trace\",instance=~\"$instances\"}[5m]))"
    }
   ]
  },
  {
   "title": "Debug msg/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(level)(rate(log4j2_events_total{job=\"zipkin\",level=\"debug\",instance=~\"$instances\"}[5m]))"
    }
   ]
  },
  {
   "title": "Info msg/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(level)(rate(log4j2_events_total{job=\"zipkin\",level=\"info\",instance=~\"$instances\"}[5m]))"
    }
   ]
  },
  {
   "title": "Warn msg/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(level)(rate(log4j2_events_total{job=\"zipkin\",level=\"warn\",instance=~\"$instances\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error msg/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(level)(rate(log4j2_events_total{job=\"zipkin\",level=\"error\",instance=~\"$instances\"}[5m]))"
    }
   ]
  },
  {
   "title": "Fatal msg/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(level)(rate(log4j2_events_total{job=\"zipkin\",level=\"fatal\",instance=~\"$instances\"}[5m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "\n# OpenZipkin\n\nFor documentation: [https://zipkin.io/](https://zipkin.io/)\n\n\n\n"
   }
  },
  {
   "title": "Messages received per transport",
   "type": "timeseries",
   "description": "Messages on left axis, Spans on right axis",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_messages_total{job=\"zipkin\",instance=~\"$instances\"}[$__interval]))\n",
     "legendFormat": "{{transport}} messages"
    }
   ]
  },
  {
   "title": "Spans received per transport",
   "type": "timeseries",
   "description": "Messages on left axis, Spans on right axis",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_spans_total{instance=~\"$instances\"}[$__interval]))\n",
     "legendFormat": "{{transport}} spans"
    }
   ]
  },
  {
   "title": "Dropped messages",
   "type": "timeseries",
   "description": "The number of messages dropped (for kafka, scribe and http)",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_messages_dropped_total{job=\"zipkin\",instance=~\"$instances\"}[$__interval]))",
     "legendFormat": "{{transport}} dropped messages"
    }
   ]
  },
  {
   "title": "Spans dropped",
   "type": "timeseries",
   "description": "The number of spans dropped (for scribe, http and kafka)",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_spans_dropped_total{instance=~\"$instances\"}[$__interval]))\n",
     "legendFormat": "{{transport}} dropped spans"
    }
   ]
  },
  {
   "title": "Bytes received per transport",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (transport)(rate(zipkin_collector_bytes_total{job=\"zipkin\",instance=~\"$instances\"}[$__interval]))",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"zipkin\",instance=~\"$instances\",uri=\"/api/v2/spans\"}[$__interval])",
     "legendFormat": "{{method}} {{uri}}  {{status}} "
    }
   ]
  },
  {
   "title": "GET Spans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, http_server_requests_seconds_bucket{job=\"zipkin\",method=\"GET\",status=\"200\",uri=\"/api/v2/spans\",instance=~\"$instances\"})",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, http_server_requests_seconds_bucket{job=\"zipkin\",method=\"GET\",status=\"200\",uri=\"/api/v2/spans\",instance=~\"$instances\"})",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "POST Spans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, http_server_requests_seconds_bucket{job=\"zipkin\",method=\"POST\",status=\"202\",uri=\"/api/v2/spans\",instance=~\"$instances\"})",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, http_server_requests_seconds_bucket{job=\"zipkin\",method=\"POST\",status=\"202\",uri=\"/api/v2/spans\",instance=~\"$instances\"})",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "System CPUs used, Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_count{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} CPUs"
    },
    {
     "expr": "system_load_average_1m{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} load"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(area,instance)(jvm_memory_used_bytes{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} {{area}} used"
    },
    {
     "expr": "sum by(area,instance)(jvm_memory_max_bytes{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} {{area}} max"
    },
    {
     "expr": "sum by(instance,id)(jvm_buffer_total_capacity_bytes{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{id}} max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_gc_pause_seconds_sum{job=\"zipkin\",instance=~\"$instances\"}[$__interval])",
     "legendFormat": "{{cause}} {{action}} duration"
    },
    {
     "expr": "delta(jvm_gc_pause_seconds_count{job=\"zipkin\",instance=~\"$instances\"}[$__interval])",
     "legendFormat": "{{cause}} {{action}} count"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance)(jvm_threads_live_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": " {{instance}} live"
    },
    {
     "expr": "sum by(instance)(jvm_threads_daemon_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} daemon"
    },
    {
     "expr": "sum by(instance)(jvm_threads_peak_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} peak"
    },
    {
     "expr": "sum by(instance)(jvm_threads_states_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}}-{{state}}"
    }
   ]
  },
  {
   "title": "JVM Classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} current"
    },
    {
     "expr": "jvm_classes_unloaded_classes_total{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} unloaded since boot"
    }
   ]
  }
 ]
}