server:
  shutdown: graceful
  servlet:
    context-path: /api
  port: 9090

spring:
  application:
    name: voxx-car-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5400/voxx_car_systems
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/voxx-car-systems
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: voxx-car-client

logging:
  level:
    org.springframework.security: trace
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

security:
  whitelist:
    urls:
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v3/api-docs

kafka:
  topic:
    model-created: model-created-topic
    model-updated: model-updated-topic
    model-deleted: model-deleted-topic
    marka-created: marka-created-topic
    marka-updated: marka-updated-topic
    marka-deleted: marka-deleted-topic
    firma-created: firma-created-topic
    firma-updated: firma-updated-topic
    firma-deleted: firma-deleted-topic
