name: CI - Build & Push

on:
  push:
    branches:
      - main
      - release/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./voxx-car-server
          file: ./voxx-car-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voxx-car-server:latest

      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./voxx-car-client
          file: ./voxx-car-client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voxx-car-client:latest
